Implement TPE algorithm
rioyokotalab/polaris pull request #1
Opened 2018-07-12 07:39 UTC by Linsho

TPEアルゴリズムをBOHB: Bayesian Optimization & Hyeprband [Falkner, Klein & Hutter ICML 2018]を元にして実装しました。（オリジナルTPEではありません）

- テストは行ってません。
- 実数値のみの取り扱いしか実装できていません。(Domainから型が取得できないため)

順序無し離散値（カテゴリ）の最適化については論文にあったので最適化する型が取得できれば実装できますが、順序あり離散値はなかったので実装できないかもしれません

2018-07-12 10:53 UTC, Linsho commented
```
python3 -m unittest discover polaris/tests
{'lr': 0.006498680976190008, 'weight_decay': 0.019420739966901426}
.
----------------------------------------------------------------------
Ran 1 test in 1.367s

OK
```

2018-07-13 09:29 UTC, sh8 commented
Domain から型取得できるようにしないとだね、、
少し修正があったので, Conflictだけ直してもらえると！

2018-07-13 10:45 UTC, Linsho commented
Confilict修正しました

2018-07-13 15:33 UTC, sh8 requested changes

2018-07-13 15:33 UTC, sh8 commented on polaris/optimizers/tpe.py
> +class tpe:
クラス名は大文字で

2018-07-13 15:33 UTC, sh8 commented on polaris/optimizers/tpe.py
> +            args=(l, g)
アルゴリズムを指定するべきだと思う！

2018-07-13 15:33 UTC, sh8 commented on polaris/params.py
> +    'tpe': tpe.tpe()
ここも `calc_next_params` に統一しよう

2018-07-13 15:34 UTC, sh8 commented
いくつか修正点投げたので, 修正お願いします！

2018-07-14 01:25 UTC, Linsho commented on polaris/optimizers/tpe.py
> +            args=(l, g)
このminimize関数はscipy optimizeのものではなく、TPE独自(論文alg2.line5~6)のものなのでアルゴリズム名などがあるものではないです

2018-07-14 01:26 UTC, Linsho commented on polaris/params.py
> +    'tpe': tpe.tpe()
TPEアルゴリズム自体のハイパーパラメータを指定できる余地を残すべきだと思うのですが、その自由度を削って関数を作った方がいいでしょうか

2018-07-14 01:29 UTC, Linsho commented
optimizersの統一方法について、このままの方がいいと思います

2018-07-19 07:00 UTC, sh8 approved these changes

2018-07-19 07:01 UTC, merged